#ifndef PARAMS_H
#define PARAMS_H




#define CTRU_N 512 /* Change this for different security strengths */
// #define CTRU_N 1024



#define CTRU_Q 769
#define CTRU_LOGQ 10


#define CTRU_SEEDBYTES CTRU_MSGBYTES


#define SHA3512_OUTPUTBYTES 64

#define CTRU_CBD1_BYTES CTRU_N/4
#define CTRU_COINBYTES_KEYGEN CTRU_CBD1_BYTES*2
#define CTRU_COINBYTES_ENC CTRU_CBD1_BYTES


#define CTRU_Q2 256  /* Change this for the ciphertext modulus */
#define CTRU_LOGQ2 8 /* Change this for the ciphertext modulus */

#define CTRU_PKE_PUBLICKEYBYTES 512*10/8
#define CTRU_PKE_CIPHERTEXTBYTES (CTRU_N)
#define CTRU_BOUND 3
#define CTRU_ETA 1

#define CTRU_Z_BYTES 32
#define CTRU_SHAREDKEYBYTES 32
#define CTRU_MSGBYTES 32
#define CTRU_PREFIXHASHBYTES 33


#define SECRETBYTES 3
#define CTRU_PKE_SECRETKEYBYTES 103
#define CTRU_PKE_SECRETKEYBYTES_1 (SECRETBYTES * CTRU_N / 8) 

#define CTRU_KEM_PUBLICKEYBYTES CTRU_PKE_PUBLICKEYBYTES
#define CTRU_KEM_SECRETKEYBYTES (CTRU_PKE_SECRETKEYBYTES + CTRU_PKE_PUBLICKEYBYTES + CTRU_Z_BYTES)
#define CTRU_KEM_CIPHERTEXTBYTES CTRU_PKE_CIPHERTEXTBYTES


#endif